import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        marginBottom: 20,
        width: '100%',
    },
    fullWidth: {
        width: '100%',
    },
    label: {
        paddingTop: 16,
        fontSize: 24,
        fontWeight: 'bold',
        color: '#555',
        marginBottom: 8,
    },
    previewContainer: {
        width: '100%',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#ddd',
        padding: 10,
    },
    imageWrapper: {
        width: '100%',
        height: 150,
        backgroundColor: '#f9f9f9',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 4,
        overflow: 'hidden',
    },
    signatureImage: {
        width: '100%',
        height: '100%',
        backgroundColor: '#fff',
    },
    clearButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ff4d4f',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 4,
        marginTop: 10,
        gap: 6,
    },
    clearButtonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 14,
    },
    collectButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#1890ff',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        gap: 8,
        elevation: 2,
        width: '100%',
    },
    collectButtonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    noSignatureText: {
        fontSize: 16,
        color: '#999',
        fontStyle: 'italic',
        paddingVertical: 10,
    },
    modalContainer: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
    },
    closeModalButton: {
        padding: 4,
    },
    canvasArea: {
        flex: 1,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 16,
    },
    canvasWrapper: {
        width: '100%',
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 8,
        overflow: 'hidden',
    },
    modalFooter: {
        flexDirection: 'row',
        marginBottom: 40,
        padding: 16,
        backgroundColor: '#fff',
        borderTopWidth: 1,
        borderTopColor: '#eee',
        gap: 12,
    },
    modalButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalButtonPrimary: {
        backgroundColor: '#1890ff',
    },
    modalButtonSecondary: {
        backgroundColor: '#f5f5f5',
        borderWidth: 1,
        borderColor: '#ccc',
    },
    modalButtonTextPrimary: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    modalButtonTextSecondary: {
        color: '#333',
        fontWeight: 'bold',
        fontSize: 16,
    },
});
