import { StyleSheet } from 'react-native';
import { colors } from '../../../../theme/colors';

export const styles = StyleSheet.create({
  button:{
    backgroundColor: colors.surface,
    width: '100%',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 15,
    padding: 8,
    alignItems: 'center',
    marginBottom: 16,
    elevation: 4,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  buttonText:{
    color: colors.textSecondary,
    fontWeight: 'bold',
    fontSize: 18,
  },
  buttonTextRemove: {
    color: colors.surface,
    fontWeight: 'bold',
  },
  labelText:{
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textSecondary,
    marginBottom: 4,
    marginLeft: 10,
  },
  buttonImg:{
    width: '49%',
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    gap: 10,
  },
  imgButtonsContainer:{
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  removeImageButton: {
    backgroundColor: colors.error,
    borderRadius: 20,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: 5,
    right: 5,
    zIndex: 10,
    elevation: 5,
  },
  selectedImage: {
    height: 125,
    width: 125,
    borderRadius: 10,
    resizeMode: 'cover',
  },
  imageItemContainer: {
    position: 'relative',
    marginBottom: 15,
    marginRight: 15,
    width: 125,
    height: 125,
    elevation: 4,
    backgroundColor: colors.surface,
    borderRadius: 10,
    overflow: 'hidden',
  },
  statusIndicator: {
    position: 'absolute',
    bottom: 5,
    right: 5,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  uploadingContainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 5,
  },
  imagePreviewContainer: {
    width: '100%',
    flex: 1,
    alignItems: 'center',
    marginBottom: 20,
    backgroundColor: colors.surface,
    padding: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    elevation: 4,
  },
  flatListContent:{
    paddingLeft: 0, 
    paddingVertical: 10,
  },
  modalBackground: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullScreenImage: {
    width: '100%',
    height: '100%',
  },
  closeModalButton: {
    position: 'absolute',
    top: 40,
    right: 20,
    zIndex: 10,
    padding: 10,
  },
  pagerView: {
    flex: 1,
    width: '100%',
  },
  page: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  pageIndicator: {
    position: 'absolute',
    top: 50,
    alignSelf: 'center',
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    zIndex: 10,
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: 15,
    paddingVertical: 5,
    borderRadius: 15,
  },
})
